import { authOptions } from '@/pages/api/auth/[...nextauth]';
import { getServerSession } from 'next-auth';
import type { Metadata } from 'next';
import AuthSession from './AuthSession';
import Menu from './_components/Menu/Menu';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang='en'>
      <head></head>
      <body className={' h-screen'}>
        <AuthSession>
          <div className=' fixed bg-gray-400 z-10 h-[10%] w-full flex items-center justify-center top-0'>
            <Menu></Menu>
          </div>
          <div className=' relative top-[10%] h-[90%]'>{children}</div>
        </AuthSession>
      </body>
    </html>
  );
}
